"""
api/main.py
-----------
Part 6 — FastAPI deployment layer for VitaTwin Digital Health Twin.

Endpoints:
  POST /analyze   — full pipeline: BERT prediction + XAI (LIME+Attention) + Insight
  POST /ask       — RAG pipeline:  retrieve similar notes + Claude LLM answer
  GET  /health    — health check
  GET  /specialty-map — returns the specialty → group mapping
  GET  /docs      — Swagger UI (auto-generated by FastAPI)

Usage:
  # Install dependencies
  pip install fastapi uvicorn python-multipart

  # Run the server
  uvicorn api.main:app --reload --host 0.0.0.0 --port 8000

  # Or from project root
  python api/main.py

  # Test with curl
  curl -X POST http://localhost:8000/analyze \
       -H "Content-Type: application/json" \
       -d '{"text": "Patient has chest pain, dyspnea and elevated troponin."}'

  curl -X POST http://localhost:8000/ask \
       -H "Content-Type: application/json" \
       -d '{"query": "What is the main concern for this patient?",
            "note": "Patient complains of chest pain and shortness of breath."}'
"""

from __future__ import annotations

import os
import sys
import time
import traceback
from pathlib import Path
from typing import List, Optional

# ── Add project root to path so local modules resolve ────────────────────────
PROJECT_ROOT = str(Path(__file__).resolve().parent.parent)
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

from fastapi import FastAPI, HTTPException, Request  # noqa: E402
from fastapi.middleware.cors import CORSMiddleware  # noqa: E402
from fastapi.responses import JSONResponse  # noqa: E402
from pydantic import BaseModel, Field  # noqa: E402

# ── Local modules ─────────────────────────────────────────────────────────────
try:
    from model.explain import explain as run_explain
    EXPLAIN_AVAILABLE = True
except Exception as e:
    EXPLAIN_AVAILABLE = False
    print(f"[WARN] explain module unavailable: {e}")

try:
    from model.insights import generate_insight
    INSIGHTS_AVAILABLE = True
except Exception as e:
    INSIGHTS_AVAILABLE = False
    print(f"[WARN] insights module unavailable: {e}")

try:
    from rag.rag import ask as rag_ask
    RAG_AVAILABLE = True
except Exception as e:
    RAG_AVAILABLE = False
    print(f"[WARN] rag module unavailable: {e}")


# ═══════════════════════════════════════════════════════════════════════════════
#  APP SETUP
# ═══════════════════════════════════════════════════════════════════════════════

app = FastAPI(
    title       = "VitaTwin Digital Health Twin API",
    description = (
        "NLP + Explainable AI + RAG system for clinical note analysis.\n\n"
        "**Endpoints:**\n"
        "- `POST /analyze` — BERT prediction + LIME/Attention XAI + Clinical Insight\n"
        "- `POST /ask`     — RAG pipeline (semantic search + Claude LLM answer)\n"
        "- `GET  /health`  — Service health check\n"
    ),
    version     = "1.0.0",
    docs_url    = "/docs",
    redoc_url   = "/redoc",
)

# ── CORS (allow all origins for development) ──────────────────────────────────
app.add_middleware(
    CORSMiddleware,
    allow_origins     = ["*"],
    allow_credentials = True,
    allow_methods     = ["*"],
    allow_headers     = ["*"],
)


# ═══════════════════════════════════════════════════════════════════════════════
#  REQUEST / RESPONSE SCHEMAS
# ═══════════════════════════════════════════════════════════════════════════════

# ── /analyze ──────────────────────────────────────────────────────────────────

class AnalyzeRequest(BaseModel):
    text: str = Field(
        ...,
        min_length  = 10,
        description = "Clinical note or patient transcription text to analyze",
        example     = (
            "Patient is a 58-year-old male presenting with chest pain, "
            "dyspnea on exertion, and elevated troponin levels. "
            "History of hypertension and type 2 diabetes."
        ),
    )
    sample_id: Optional[str] = Field(
        default     = None,
        description = "Optional identifier for this sample (used in saved output filenames)",
        example     = "patient_001",
    )
    save_plots: Optional[bool] = Field(
        default     = False,
        description = "If true, save LIME and attention PNG plots to model/explanations/",
    )
    lime_samples: Optional[int] = Field(
        default     = 150,
        ge          = 50,
        le          = 500,
        description = "Number of LIME perturbation samples (higher = more accurate, slower)",
    )


class DetectedSignal(BaseModel):
    term   : str
    weight : int
    label  : str


class AttentionToken(BaseModel):
    token           : str
    attention_score : float


class AnalyzeResponse(BaseModel):
    sample_id              : str
    # Prediction
    predicted_group        : str
    group_confidence       : float
    predicted_specialty    : str
    specialty_confidence   : float
    # XAI
    lime_tokens            : dict
    attention_tokens       : List[AttentionToken]
    top_influential_terms  : List[str]
    # Insight
    risk_level             : str
    risk_score             : int
    risk_emoji             : str
    detected_signals       : List[DetectedSignal]
    summary                : str
    recommended_actions    : List[str]
    monitoring_parameters  : List[str]
    confidence_note        : str
    # Meta
    processing_time_sec    : float


# ── /ask ──────────────────────────────────────────────────────────────────────

class AskRequest(BaseModel):
    query: str = Field(
        ...,
        min_length  = 3,
        description = "Clinical question to answer using the RAG pipeline",
        example     = "What is the main concern for this patient?",
    )
    note: Optional[str] = Field(
        default     = None,
        description = "Patient note to ground the query (optional)",
        example     = (
            "Patient has chest pain, dyspnea, and elevated troponin."
        ),
    )
    top_k: Optional[int] = Field(
        default     = 5,
        ge          = 1,
        le          = 20,
        description = "Number of similar notes to retrieve from the vector store",
    )
    retrieve_only: Optional[bool] = Field(
        default     = False,
        description = "If true, skip LLM generation and return retrieved notes only",
    )
    api_key: Optional[str] = Field(
        default     = None,
        description = (
            "Anthropic API key. If not provided, uses ANTHROPIC_API_KEY env var."
        ),
    )


class RetrievedNote(BaseModel):
    idx          : int
    specialty    : str
    description  : str
    transcription: str
    sample_name  : str
    score        : float


class AskResponse(BaseModel):
    query           : str
    note_context    : str
    retrieved       : List[RetrievedNote]
    answer          : str
    processing_time_sec : float


# ── /health ───────────────────────────────────────────────────────────────────

class HealthResponse(BaseModel):
    status          : str
    explain_module  : bool
    insights_module : bool
    rag_module      : bool
    rag_index_built : bool
    model_path      : str
    message         : str


# ═══════════════════════════════════════════════════════════════════════════════
#  MIDDLEWARE — request timing
# ═══════════════════════════════════════════════════════════════════════════════

@app.middleware("http")
async def add_process_time_header(request: Request, call_next):
    start    = time.time()
    response = await call_next(request)
    response.headers["X-Process-Time"] = str(round(time.time() - start, 4))
    return response


# ═══════════════════════════════════════════════════════════════════════════════
#  GLOBAL EXCEPTION HANDLER
# ═══════════════════════════════════════════════════════════════════════════════

@app.exception_handler(Exception)
async def global_exception_handler(request: Request, exc: Exception):
    tb = traceback.format_exc()
    return JSONResponse(
        status_code = 500,
        content     = {
            "error"     : str(exc),
            "traceback" : tb,
            "path"      : str(request.url),
        },
    )


# ═══════════════════════════════════════════════════════════════════════════════
#  ENDPOINTS
# ═══════════════════════════════════════════════════════════════════════════════

# ── GET /health ───────────────────────────────────────────────────────────────

@app.get(
    "/health",
    response_model = HealthResponse,
    summary        = "Health check",
    tags           = ["System"],
)
def health_check():
    """
    Returns the health status of the API and availability of each module.
    Use this to confirm the server is running before sending inference requests.
    """
    model_path     = os.path.join(PROJECT_ROOT, "model", "saved_model", "level1")
    rag_index_path = os.path.join(PROJECT_ROOT, "rag", "store", "index.faiss")

    model_exists     = os.path.isdir(model_path)
    rag_index_exists = os.path.isfile(rag_index_path)

    all_ok = EXPLAIN_AVAILABLE and INSIGHTS_AVAILABLE and model_exists

    return HealthResponse(
        status          = "ok" if all_ok else "degraded",
        explain_module  = EXPLAIN_AVAILABLE,
        insights_module = INSIGHTS_AVAILABLE,
        rag_module      = RAG_AVAILABLE,
        rag_index_built = rag_index_exists,
        model_path      = model_path,
        message         = (
            "All systems operational."
            if all_ok
            else "Some modules unavailable — check logs."
        ),
    )


# ── GET /specialty-map ────────────────────────────────────────────────────────

@app.get(
    "/specialty-map",
    summary = "Specialty to group mapping",
    tags    = ["System"],
)
def specialty_map():
    """Returns the full specialty → broad group mapping used by the classifier."""
    from model.train import SPECIALTY_TO_GROUP
    return {"specialty_to_group": SPECIALTY_TO_GROUP}


# ── POST /analyze ─────────────────────────────────────────────────────────────

@app.post(
    "/analyze",
    response_model = AnalyzeResponse,
    summary        = "Analyze a clinical note",
    tags           = ["Inference"],
)
def analyze(request: AnalyzeRequest):
    """
    ## Full VitaTwin Analysis Pipeline

    Given a clinical note text, this endpoint runs:

    1. **BERT Prediction** — Hierarchical Bio_ClinicalBERT classifies the note
       into a broad medical group (Level 1) and exact specialty (Level 2)

    2. **Explainable AI** — LIME token importance + attention weight extraction
       identify which clinical terms drove the prediction

    3. **Insight Generation** — Risk scoring, red-flag signal detection,
       and recommended clinical actions

    ### Returns
    - Predicted specialty + confidence
    - Top influential clinical terms (LIME + Attention merged)
    - Risk level (Low / Moderate / High / Critical)
    - Detected clinical signals (e.g. "chest pain", "elevated troponin")
    - Recommended actions and monitoring parameters
    """
    if not EXPLAIN_AVAILABLE:
        raise HTTPException(
            status_code = 503,
            detail      = "Explain module unavailable. Check model/explain.py and saved model.",
        )
    if not INSIGHTS_AVAILABLE:
        raise HTTPException(
            status_code = 503,
            detail      = "Insights module unavailable. Check model/insights.py.",
        )

    t0        = time.time()
    sample_id = request.sample_id or f"api_{int(t0)}"

    try:
        # ── Step 1+2: Explain (prediction + XAI) ─────────────────────────────
        explain_report = run_explain(
            request.text,
            sample_id    = sample_id,
            save_plots   = request.save_plots,
            lime_samples = request.lime_samples,
        )

        # ── Step 3: Insight ───────────────────────────────────────────────────
        insight = generate_insight(explain_report)

    except FileNotFoundError as e:
        raise HTTPException(
            status_code = 503,
            detail      = f"Model not found: {e}. Run train.py first.",
        )
    except Exception as e:
        raise HTTPException(
            status_code = 500,
            detail      = f"Analysis failed: {e}",
        )

    processing_time = round(time.time() - t0, 3)

    return AnalyzeResponse(
        sample_id             = sample_id,
        predicted_group       = explain_report["predicted_group"],
        group_confidence      = explain_report["group_confidence"],
        predicted_specialty   = explain_report["predicted_specialty"],
        specialty_confidence  = explain_report["specialty_confidence"],
        lime_tokens           = explain_report.get("lime_tokens", {}),
        attention_tokens      = [
            AttentionToken(**t)
            for t in explain_report.get("attention_tokens", [])
        ],
        top_influential_terms = explain_report.get("top_influential_terms", []),
        risk_level            = insight["risk_level"],
        risk_score            = insight["risk_score"],
        risk_emoji            = insight["risk_emoji"],
        detected_signals      = [
            DetectedSignal(**s) for s in insight.get("detected_signals", [])
        ],
        summary               = insight["summary"],
        recommended_actions   = insight["recommended_actions"],
        monitoring_parameters = insight["monitoring_parameters"],
        confidence_note       = insight["confidence_note"],
        processing_time_sec   = processing_time,
    )


# ── POST /ask ─────────────────────────────────────────────────────────────────

@app.post(
    "/ask",
    response_model = AskResponse,
    summary        = "Ask a clinical question using RAG",
    tags           = ["RAG"],
)
def ask(request: AskRequest):
    """
    ## RAG (Retrieval-Augmented Generation) Pipeline

    Given a clinical query (and optionally a patient note), this endpoint:

    1. **Embeds** the query using Sentence Transformers (`all-MiniLM-L6-v2`)
    2. **Retrieves** the top-K most semantically similar notes from the FAISS vector store
    3. **Generates** a grounded clinical answer using Claude (Anthropic API)

    ### Example queries
    - *"What is the main concern for this patient?"*
    - *"Which patients show signs of cardiac risk?"*
    - *"What follow-up is recommended for this presentation?"*

    ### Note
    - The RAG index must be built first: `python rag/rag.py --build --csv data/notes.csv`
    - Set `ANTHROPIC_API_KEY` environment variable or pass `api_key` in the request body
    - Set `retrieve_only: true` to skip LLM generation and just return similar notes
    """
    if not RAG_AVAILABLE:
        raise HTTPException(
            status_code = 503,
            detail      = "RAG module unavailable. Check rag/rag.py.",
        )

    # Check index exists
    rag_index_path = os.path.join(PROJECT_ROOT, "rag", "store", "index.faiss")
    if not os.path.isfile(rag_index_path):
        raise HTTPException(
            status_code = 503,
            detail      = (
                "RAG vector index not found. "
                "Build it first: python rag/rag.py --build --csv data/notes.csv"
            ),
        )

    t0 = time.time()

    try:
        result = rag_ask(
            query         = request.query,
            note_context  = request.note,
            top_k         = request.top_k,
            retrieve_only = request.retrieve_only,
            api_key       = request.api_key,
        )
    except Exception as e:
        raise HTTPException(
            status_code = 500,
            detail      = f"RAG pipeline failed: {e}",
        )

    processing_time = round(time.time() - t0, 3)

    retrieved_notes = [
        RetrievedNote(
            idx           = r.get("idx", 0),
            specialty     = r.get("specialty", ""),
            description   = r.get("description", ""),
            transcription = r.get("transcription", ""),
            sample_name   = r.get("sample_name", ""),
            score         = r.get("score", 0.0),
        )
        for r in result.get("retrieved", [])
    ]

    return AskResponse(
        query               = result["query"],
        note_context        = result.get("note_context", ""),
        retrieved           = retrieved_notes,
        answer              = result.get("answer", ""),
        processing_time_sec = processing_time,
    )


# ── POST /analyze-and-ask  (bonus: combined pipeline) ─────────────────────────

class AnalyzeAndAskRequest(BaseModel):
    text: str = Field(
        ...,
        min_length  = 10,
        description = "Clinical note text",
        example     = (
            "Patient is a 58-year-old male with chest pain, "
            "dyspnea, and elevated troponin."
        ),
    )
    query: Optional[str] = Field(
        default     = "What is the main concern for this patient and what actions are recommended?",
        description = "Question to answer via RAG after analyzing the note",
    )
    lime_samples : Optional[int]  = Field(default=100, ge=50, le=500)
    save_plots   : Optional[bool] = Field(default=False)
    retrieve_only: Optional[bool] = Field(default=False)
    api_key      : Optional[str]  = Field(default=None)


@app.post(
    "/analyze-and-ask",
    summary = "Full pipeline: analyze note + RAG answer",
    tags    = ["Inference"],
)
def analyze_and_ask(request: AnalyzeAndAskRequest):
    """
    ## Combined Endpoint

    Runs the full VitaTwin pipeline in one call:
    1. BERT prediction + XAI + Insight (from `/analyze`)
    2. RAG retrieval + Claude answer (from `/ask`) — using the note text as context

    Ideal for the frontend demo where both results are needed together.
    """
    t0        = time.time()
    sample_id = f"combined_{int(t0)}"

    # ── Analyze ────────────────────────────────────────────────────────────
    analyze_result = None
    if EXPLAIN_AVAILABLE and INSIGHTS_AVAILABLE:
        try:
            explain_report = run_explain(
                request.text,
                sample_id    = sample_id,
                save_plots   = request.save_plots,
                lime_samples = request.lime_samples,
            )
            insight = generate_insight(explain_report)
            analyze_result = {
                "predicted_group"      : explain_report["predicted_group"],
                "group_confidence"     : explain_report["group_confidence"],
                "predicted_specialty"  : explain_report["predicted_specialty"],
                "specialty_confidence" : explain_report["specialty_confidence"],
                "top_influential_terms": explain_report["top_influential_terms"],
                "lime_tokens"          : explain_report.get("lime_tokens", {}),
                "risk_level"           : insight["risk_level"],
                "risk_score"           : insight["risk_score"],
                "risk_emoji"           : insight["risk_emoji"],
                "detected_signals"     : insight["detected_signals"],
                "summary"              : insight["summary"],
                "recommended_actions"  : insight["recommended_actions"],
                "monitoring_parameters": insight["monitoring_parameters"],
                "confidence_note"      : insight["confidence_note"],
            }
        except Exception as e:
            analyze_result = {"error": str(e)}

    # ── RAG Ask ────────────────────────────────────────────────────────────
    rag_result = None
    rag_index_path = os.path.join(PROJECT_ROOT, "rag", "store", "index.faiss")
    if RAG_AVAILABLE and os.path.isfile(rag_index_path):
        try:
            rag_result = rag_ask(
                query         = request.query,
                note_context  = request.text,
                top_k         = 5,
                retrieve_only = request.retrieve_only,
                api_key       = request.api_key,
            )
        except Exception as e:
            rag_result = {"error": str(e)}

    return {
        "sample_id"         : sample_id,
        "analysis"          : analyze_result,
        "rag"               : rag_result,
        "processing_time_sec": round(time.time() - t0, 3),
    }


# ═══════════════════════════════════════════════════════════════════════════════
#  ROOT
# ═══════════════════════════════════════════════════════════════════════════════

@app.get("/", tags=["System"])
def root():
    return {
        "service" : "VitaTwin Digital Health Twin API",
        "version" : "1.0.0",
        "docs"    : "/docs",
        "health"  : "/health",
        "endpoints": {
            "POST /analyze"         : "BERT + XAI + Insight for a clinical note",
            "POST /ask"             : "RAG pipeline — retrieve similar notes + LLM answer",
            "POST /analyze-and-ask" : "Full combined pipeline",
            "GET  /health"          : "Service health check",
            "GET  /specialty-map"   : "Specialty → group mapping",
        },
    }


# ═══════════════════════════════════════════════════════════════════════════════
#  RUN
# ═══════════════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    import uvicorn

    print("\n" + "="*60)
    print("  VitaTwin Digital Health Twin API")
    print("="*60)
    print(f"  Explain module  : {'✓' if EXPLAIN_AVAILABLE  else '✗  (check model/explain.py)'}")
    print(f"  Insights module : {'✓' if INSIGHTS_AVAILABLE else '✗  (check model/insights.py)'}")
    print(f"  RAG module      : {'✓' if RAG_AVAILABLE      else '✗  (check rag/rag.py)'}")
    print("\n  Swagger UI → http://localhost:8000/docs")
    print("  Health     → http://localhost:8000/health")
    print("="*60 + "\n")

    uvicorn.run(
        "api.main:app",
        host        = "0.0.0.0",
        port        = 8000,
        reload      = True,
        reload_dirs = [PROJECT_ROOT],
    )